/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/escala/cargos/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista cargos */
        get: operations["escala_api_cargo_router_listar_cargos"];
        put?: never;
        /** Cria um novo cargo */
        post: operations["escala_api_cargo_router_cria_um_novo_cargo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/escala/cargos/{cargo_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Busca um cargo por ID */
        get: operations["escala_api_cargo_router_busca_cargo_por_id"];
        put?: never;
        post?: never;
        /** Exclui um cargo */
        delete: operations["escala_api_cargo_router_exclui_um_cargo"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/escala/instrumentos/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista instrumentos */
        get: operations["escala_api_instrumento_router_listar_instrumentos"];
        put?: never;
        /** Cria um novo instrumento */
        post: operations["escala_api_instrumento_router_cria_um_novo_instrumento"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/escala/instrumentos/{instrumento_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Busca um instrumento por ID */
        get: operations["escala_api_instrumento_router_busca_instrumento_por_id"];
        put?: never;
        post?: never;
        /** Exclui um instrumento */
        delete: operations["escala_api_instrumento_router_exclui_um_instrumento"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/escala/pessoas/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista pessoas */
        get: operations["escala_api_pessoa_router_listar_pessoas"];
        put?: never;
        /** Cria uma nova pessoa */
        post: operations["escala_api_pessoa_router_cria_uma_nova_pessoa"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/escala/pessoas/{pessoa_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Busca pessoa por ID */
        get: operations["escala_api_pessoa_router_busca_pessoa_por_id"];
        /** Atualiza uma pessoa */
        put: operations["escala_api_pessoa_router_atualiza_uma_pessoa"];
        post?: never;
        /** Exclui uma pessoa */
        delete: operations["escala_api_pessoa_router_exclui_uma_pessoa"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/escala/escalas/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista escalas */
        get: operations["escala_api_escala_router_listar_escalas"];
        put?: never;
        /** Cria uma escala */
        post: operations["escala_api_escala_router_cria_uma_nova_escala"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/escala/escalas/{escala_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Busca escala por ID */
        get: operations["escala_api_escala_router_busca_escala_por_id"];
        /** Atualiza uma escala */
        put: operations["escala_api_escala_router_atualiza_uma_escala"];
        post?: never;
        /** Exclui uma escala */
        delete: operations["escala_api_escala_router_exclui_uma_escala"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CargoSaidaGet */
        CargoSaidaGet: {
            /** ID */
            id?: number | null;
            /** Nome */
            nome: string;
        };
        /** CargoSaidaPost */
        CargoSaidaPost: {
            /** Id */
            id: number;
        };
        /** CargoEntradaPost */
        CargoEntradaPost: {
            /** Nome */
            nome: string;
        };
        /** CargoSaidaDelete */
        CargoSaidaDelete: {
            /** Success */
            success: boolean;
        };
        /** InstrumentoSaidaGet */
        InstrumentoSaidaGet: {
            /** ID */
            id?: number | null;
            /** Nome */
            nome: string;
        };
        /** InstrumentoSaidaPost */
        InstrumentoSaidaPost: {
            /** Id */
            id: number;
        };
        /** InstrumentoEntradaPost */
        InstrumentoEntradaPost: {
            /** Nome */
            nome: string;
        };
        /** InstrumentoSaidaDelete */
        InstrumentoSaidaDelete: {
            /** Success */
            success: boolean;
        };
        /** PessoaSaidaGet */
        PessoaSaidaGet: {
            /** ID */
            id?: number | null;
            /** Nome */
            nome: string;
            /** Email */
            email: string;
            /** Telefone */
            telefone: string;
        };
        /** PessoaSaidaPost */
        PessoaSaidaPost: {
            /** Id */
            id: number;
        };
        /** PessoaEntradaPost */
        PessoaEntradaPost: {
            /** Nome */
            nome: string;
            /** Email */
            email: string;
            /** Telefone */
            telefone: string;
        };
        /** PessoaSaidaPut */
        PessoaSaidaPut: {
            /** Success */
            success: boolean;
        };
        /** PessoaEntradaPut */
        PessoaEntradaPut: {
            /** Nome */
            nome: string;
            /** Email */
            email: string;
            /** Telefone */
            telefone: string;
        };
        /** PessoaSaidaDelete */
        PessoaSaidaDelete: {
            /** Success */
            success: boolean;
        };
        /** EscalaSaidaGet */
        EscalaSaidaGet: {
            pessoa: components["schemas"]["PessoaSaidaGet"];
            /** Cargos */
            cargos: components["schemas"]["CargoSaidaGet"][];
            /** Instrumento */
            instrumento?: components["schemas"]["InstrumentoSaidaGet"][] | null;
            /** ID */
            id?: number | null;
            /**
             * Data
             * Format: date
             */
            data: string;
            /** Descrição */
            descricao?: string | null;
        };
        /** EscalaSaidaPost */
        EscalaSaidaPost: {
            /** Id */
            id: number;
        };
        /** EscalaEntradaPost */
        EscalaEntradaPost: {
            /** Cargo Ids */
            cargo_ids: number[];
            /** Pessoa Id */
            pessoa_id: number;
            /**
             * Instrumento Ids
             * @default []
             */
            instrumento_ids: number[] | null;
            /** Descricao */
            descricao?: string | null;
            /**
             * Data
             * Format: date
             */
            data: string;
        };
        /** EscalaSaidaPut */
        EscalaSaidaPut: {
            /** Success */
            success: boolean;
        };
        /** EscalaEntradaPut */
        EscalaEntradaPut: {
            /** Cargo Ids */
            cargo_ids: number[];
            /** Pessoa Id */
            pessoa_id: number;
            /**
             * Instrumento Ids
             * @default []
             */
            instrumento_ids: number[] | null;
            /** Descricao */
            descricao?: string | null;
            /**
             * Data
             * Format: date
             */
            data: string;
        };
        /** EscalaSaidaDelete */
        EscalaSaidaDelete: {
            /** Success */
            success: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    escala_api_cargo_router_listar_cargos: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CargoSaidaGet"][];
                };
            };
        };
    };
    escala_api_cargo_router_cria_um_novo_cargo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CargoEntradaPost"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CargoSaidaPost"];
                };
            };
        };
    };
    escala_api_cargo_router_busca_cargo_por_id: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cargo_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CargoSaidaGet"];
                };
            };
        };
    };
    escala_api_cargo_router_exclui_um_cargo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cargo_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CargoSaidaDelete"];
                };
            };
        };
    };
    escala_api_instrumento_router_listar_instrumentos: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstrumentoSaidaGet"][];
                };
            };
        };
    };
    escala_api_instrumento_router_cria_um_novo_instrumento: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InstrumentoEntradaPost"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstrumentoSaidaPost"];
                };
            };
        };
    };
    escala_api_instrumento_router_busca_instrumento_por_id: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instrumento_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstrumentoSaidaGet"];
                };
            };
        };
    };
    escala_api_instrumento_router_exclui_um_instrumento: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instrumento_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstrumentoSaidaDelete"];
                };
            };
        };
    };
    escala_api_pessoa_router_listar_pessoas: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PessoaSaidaGet"][];
                };
            };
        };
    };
    escala_api_pessoa_router_cria_uma_nova_pessoa: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PessoaEntradaPost"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PessoaSaidaPost"];
                };
            };
        };
    };
    escala_api_pessoa_router_busca_pessoa_por_id: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pessoa_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PessoaSaidaGet"];
                };
            };
        };
    };
    escala_api_pessoa_router_atualiza_uma_pessoa: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pessoa_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PessoaEntradaPut"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PessoaSaidaPut"];
                };
            };
        };
    };
    escala_api_pessoa_router_exclui_uma_pessoa: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pessoa_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PessoaSaidaDelete"];
                };
            };
        };
    };
    escala_api_escala_router_listar_escalas: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EscalaSaidaGet"][];
                };
            };
        };
    };
    escala_api_escala_router_cria_uma_nova_escala: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EscalaEntradaPost"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EscalaSaidaPost"];
                };
            };
        };
    };
    escala_api_escala_router_busca_escala_por_id: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                escala_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EscalaSaidaGet"];
                };
            };
        };
    };
    escala_api_escala_router_atualiza_uma_escala: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                escala_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EscalaEntradaPut"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EscalaSaidaPut"];
                };
            };
        };
    };
    escala_api_escala_router_exclui_uma_escala: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                escala_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EscalaSaidaDelete"];
                };
            };
        };
    };
}
